name: flutter_onscreen_keyboard_workspace

publish_to: none

environment:
  sdk: ^3.8.0

workspace:
  - packages/flutter_onscreen_keyboard

dev_dependencies:
  melos: ^6.3.3

melos:
  repository: https://github.com/albinpk/flutter_onscreen_keyboard
  sdkPath: .fvm/flutter_sdk
  command:
    version:
      hooks:
        # Update the version in readme
        preCommit: bash -c "$(curl -s https://raw.githubusercontent.com/albinpk/flutter_cora/refs/heads/dev/scripts/preVersion.sh)"
        post: flutter pub publish --dry-run --directory=packages/flutter_onscreen_keyboard
